rvm: 2.0.0

script: bundle exec rake publish ALLOW_DIRTY=true

notifications:
  # Disable build status email notifications, until the issue with forks is fixed
  email: false
  # IRC notification
  irc: "chat.freenode.net#oxidemod"
