rvm: 2.0.0

# Run deployment script
script: bundle exec rake travis

notifications:
  # Disable build status email notifications, until the issue with forks is fixed
  email: false
  # IRC notification
  irc: "chat.freenode.net#oxidemod"

# Environmental system variables
env:
  global:
    # Super secure, encrypted variables! Ssssh!
    - secure: "dOdEOS/01TV2inXo5WjQs5iFmHTYtElPWncy8AZfVn1oV5K7dbQViuQrFDQQ0YryeYM01fcUDtLMQtEtzFqYIEvp/+LRsOSp2scgayJoi4kli1TM5EIbtY8DO3ly1+HsjklH2y0xW81WLsKWbQHMSAOSsq2jWOKqSwzkBkpDjGc="
