rvm: 2.0.0

script: bundle exec rake build
after_success: bundle exec rake publish

notifications:
  # Disable build status email notifications, until the issue with forks is fixed
  email: false
  # IRC notification
  irc: "chat.freenode.net#oxidemod"
